### ISSUE TITLE
Tag names not correct for automatic packagist sync

### ISSUE THREAD

**Issue by jdambacher** [PAYONE-GmbH/shopware-6#14]
The tags for this repo are not following the packagist rules for auto sync. See https://packagist.org/about => "Managing package versions".

They should be renamed to "v.1.0.0-RC2" or "1.0.0-RC2". Currently it's not possible to get the latest tag with composer.

**Comment by hreinberger** [comment]
Hi, thanks for the issue! We're following semver with our tags, which states that RCs should be tagged like x.y.z-rc.1 https://semver.org/#spec-item-9 
Packagist seems to somewhat deviate from that. We'll streamline our versioning until the final 1.0.0 release, so that should be sorted out with the final 1.0.0

**Comment by jdambacher** [comment]
@hreinberger Thanks for the reply.

**Comment by hreinberger** [comment]
Aaaaaand there it is! https://github.com/PAYONE-GmbH/shopware-6/releases/tag/v1.0.0
