### ISSUE TITLE
headless support

### ISSUE THREAD

**Issue by amin212121** [PAYONE-GmbH/shopware-6#189]
do you support headless? Do you provide API routes for credit card where I can provide card data from my front shop?

**Comment by hreinberger** [comment]
Hi, we've developed the plugin with headless use cases in mind, but haven't had a full project using it yet. For credit card payments, you should use our JS library and the [hosted iFrames](https://docs.payone.com/display/public/INT/Modern+Credit+Card+Checkout) in your checkout. This way, you can safely tokenize credit card data with only the client and PAYONE systems involved. The actual payment request from the shop can then use the credit card token instead of live credit card data.

Other payment methods that have frontend components like certain BNPL types or SEPA direct debit could also be a bit more challenging to implement.

We'd love to support you on your journey to running shopware 6 headless with our plugin though. If you have any specific questions, feel free to contact us at integrations[at]payone[dot]com
