### ISSUE TITLE
Admin: partial refund instead of full refund

### ISSUE THREAD

**Issue by hgnb99** [PAYONE-GmbH/shopware-6#312]
## Problem Description 
When creating an refund via backend -> order detail -> payone -> [Refund]-Button 
it will create a partial refund and set order state `partially_refunded' even if all line items are selected ... it should create full refund instead. ... 

## System Info
Shopware 6.5.8.8
PayonePayment 6.0.1

## possible solution . 

add maxRefundAmout var like in v5.0.2 ...
[refund_button .patch.txt](https://github.com/user-attachments/files/15878028/refund_button.patch.txt)

**Comment by janteuber** [comment]
Hello @hgnb99 ,

Thank you for your message.

The problem with the old version of the plugin was that after a partial capture, the full capture button no longer worked because a full capture was no longer possible.

For this reason, we decided to look at which items were still in the order and then create a refund for these items.
