### ISSUE TITLE
PWA-ready?

### ISSUE THREAD

**Issue by azngeek** [PAYONE-GmbH/shopware-6#98]
Hello, is this plugin ready for the pwa-integration in shopware?

**Comment by andreasemer** [comment]
Can you give us an update here please Payone?

**Comment by hreinberger** [comment]
Hi there, we're currently doing a massive refactoring of our plugin in order to be able to support completely headless operation. In some payment methods like SEPA and credit card there's always a frontend component involved (for mandate management and credit card tokenization), so we'd love to dive deeper into this if you have a specific use case.

**Comment by hreinberger** [comment]
Maybe relevant for this: in #118 we started to use the API for store-front related actions like managing stored credit cards and SEPA mandates. There's still some storefront controllers involved for payment methods like PayPal ECS or Payolution, where our plugin renders elements in the storefront or there's lots of redirects involved.
